name: implicit_sindy
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - adwaita-icon-theme=48.0
  - asttokens=3.0.0
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - comm=0.2.1
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - epoxy=1.5.10
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - glib-tools=2.84.0
  - graphite2=1.3.13
  - graphviz=12.2.1
  - gtk3=3.24.43
  - gts=0.7.6
  - harfbuzz=11.0.0
  - hicolor-icon-theme=0.17
  - icu=75.1
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcups=2.3.3
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libglib=2.84.0
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libpng=1.6.47
  - librsvg=2.58.4
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=24.2
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.8.0
  - pip=25.0
  - pixman=0.44.2
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - python=3.10.13
  - python-dateutil=2.9.0post0
  - python-graphviz=0.20.3
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.2
  - stack_data=0.2.0
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wayland=1.23.1
  - wcwidth=0.2.5
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.3.0
      - clarabel==0.10.0
      - cmake==4.0.0
      - contourpy==1.3.2
      - cvxpy==1.6.5
      - cycler==0.12.1
      - derivative==0.6.3
      - fastjsonschema==2.21.1
      - fonttools==4.57.0
      - importlib-metadata==8.6.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - narwhals==1.35.0
      - nbformat==5.10.4
      - numpy==1.23.5
      - osqp==1.0.3
      - pandas==2.2.3
      - pillow==11.2.1
      - plotly==6.0.1
      - pyparsing==3.2.3
      - pysindy==1.7.5
      - pytz==2025.2
      - referencing==0.36.2
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scs==3.2.7.post2
      - seaborn==0.13.2
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tqdm-joblib==0.0.4
      - tzdata==2025.2
      - zipp==3.21.0
